### ISSUE TITLE
Create a Figma

### ISSUE THREAD

**Issue by asparadise33** [frankcampos/Second-Life-Recycling#13]
- [x] Create a Figma as a visual roadmap to our project

**Comment by TrevorMustoe** [comment]
@asparadise33 Can you attach a link to the Figma on this ticket?

**Comment by asparadise33** [comment]
@TrevorMustoe Here you are :-)

https://www.figma.com/board/kgmZK81UbmjyKW6mE7Ls4G/Second-Life-Recycling?node-id=63-821&t=iS99h3pI1MgzRKo7-0
